ritu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls',namespace="users")),
    path('', include('ritu_web_app.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ritu_web_app/urls.py
"""Defines URL patterns for ritu_web_app"""

from django.urls import path

from . import views

app_name= 'ritu_web_app'
urlpatterns=[
    # Home page
    path('', views.homepage, name='homepage'),
    path('aboutUs',views.aboutUs,name='aboutUs'),
    path('contactUs',views.contactUs,name='contactUs'),
    path('finalMessage',views.finalMessage,name='finalMessage'),
    path('leaderboard',views.showLeaderboard,name='leaderboard'),
    path('marketplace',views.marketplace,name='marketplace'),

    path('task1',views.task1,name='task1'),
    path('task2',views.task2,name='task2'),
    path('task3',views.task3,name='task3'),
    path('verification',views.verification,name='verificationPage'),
    path('profile',views.profileCard,name='profileCard'),
    path('FinalMessege',views.FinalMessege,name='FinalMessege'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name= 'users'
urlpatterns = [
    #Include default auth urls
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('signup', views.signupPage, name='signup'),
    #loginpage
    path('login',views.login, name='login'),
    path('menu',views.menu,name='menu'),
]

ritu_web_app/models.py
from configparser import MAX_INTERPOLATION_DEPTH
from distutils.archive_util import make_zipfile
from distutils.command.upload import upload
import email
from email import message
from email.policy import default
from ftplib import MAXLINE
from hashlib import blake2b
from shutil import _ntuple_diskusage
from types import TracebackType
from django.db import models

# Players table
class Players(models.Model):
    username=models.CharField(primary_key=True,null=False,blank=False,max_length=40)
    fullname=models.CharField(null=False,blank=False,max_length=50)
    mobileNumber=models.CharField(null=False,blank=False,max_length=15)
    email=models.EmailField(null=False,blank=False,max_length=100)
    address=models.CharField(null=False,blank=False,max_length=100)
    picture=models.ImageField(default='default.png',null=True,blank=True,upload_to='images/')

    def __str__(self) :
        return self.username

#Proof of task 1 submission : multimedia 
class Task1Proof(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE)
    #taskid= here comes the taskid field which will be generated from the tasktable
    proof=models.FileField(null=True,blank=True,upload_to='task1/')
    
    def __str(self):
        return self.player

#Proof of task 2 submission : multimedia 
class Task2Proof(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE)
    #taskid= here comes the taskid field which will be generated from the tasktable
    proof=models.FileField(null=True,blank=True,upload_to='task2/')
    
    def __str(self):
        return self.player

#Proof of task 3 submission : multimedia 
class Task3Proof(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE)
    #taskid= here comes the taskid field which will be generated from the tasktable
    proof=models.FileField(null=True,blank=True,upload_to='task3/')
    
    def __str(self):
        return self.player  

#Proof of task 1 submission : URL of facebook post/drive link
class Task1Text(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE,db_constraint=False)
    text=models.URLField(max_length=200,null=False,blank=False,verbose_name="text")
    time_added = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    earnedPoints=models.FloatField(null=True,blank=True,verbose_name='Points')
    def __str__(self):
        return f"{self.text[:50]}..."

#Proof of task 2 submission : URL of facebook post/drive link
class Task2Text(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE,db_constraint=False)
    text=models.URLField(max_length=200,null=False,blank=False,verbose_name="text")
    time_added = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    earnedPoints=models.FloatField(null=True,blank=True,verbose_name='Points')

    def __str__(self):
        return f"{self.text[:50]}..."

#Proof of task 3 submission : URL of facebook post/drive link
class Task3Text(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE,db_constraint=False)
    text=models.URLField(max_length=200,null=False,blank=False,verbose_name="text")
    time_added = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    earnedPoints=models.FloatField(null=True,blank=True,verbose_name='Points')

    def __str__(self):
        return f"{self.text[:50]}..."



#Points table for leaderboard
class Leaderboard(models.Model):
    player=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,null=True,blank=True,verbose_name="Name")
    earnedPoints=models.FloatField(null=True,blank=True,verbose_name='Points')

    def __str__(self):
        return self.player.username



#The items to be sold in marketplace for various tasks
class Marketplace(models.Model):
    product_name=models.CharField(null=False,blank=False,max_length=100,verbose_name="Name")
    product_desc=models.CharField(null=False,blank=False,max_length=150,verbose_name="Description")
    product_price=models.CharField(max_length=20,null=False,blank=False,verbose_name="Price")
    product_img=models.ImageField(null=True,blank=True,verbose_name="Image",upload_to='marketplace/')

    def __str__(self):
        return self.product_name


class Orders(models.Model):
    playerID=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE)
    productID=models.ForeignKey(Marketplace,null=False, blank=False,on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.playerID




#Databases for orders for ADMIN purpose

class OrderData(models.Model):
    playerID=models.ForeignKey(Players,null=False,blank=False,on_delete=models.CASCADE)
    playerName=models.CharField(null=True,blank=True,max_length=100)
    productid=models.CharField(null=False,blank=False,max_length=20)
    product_name=models.CharField(null=False,blank=False, max_length=100)
    productPrice=models.CharField(null=False,blank=False,max_length=10)
    deliveryAddress=models.CharField(null=True,blank=True,max_length=300)
    contactNum=models.CharField(null=True,blank=True,max_length=20)
    time=models.DateTimeField(auto_now_add=True,null=True,blank=True)
    def __str__(self):
        return self.product_name

class Messages(models.Model):
    name=models.CharField(max_length=50,null=False,blank=False)
    email=models.EmailField(max_length=50,null=False,blank=False)
    message=models.CharField(max_length=500,null=True,blank=True)
    
    def __str__(self) :
        return self.email

ritu_web_app/views.py
import enum
from operator import add
from tokenize import Double, Intnumber
from xmlrpc.client import DateTime
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from . import addTextTask
from . import updatedLeaderboard
from . import marketPlace
from . import player
from . import orders
from .models import Leaderboard, Marketplace, Players,Messages
from django.core import serializers
from datetime import datetime
from django.contrib import messages
import time

def homepage(request):
    """The home page for ritu"""
    return render(request, 'ritu_web_app/homepage.html')

def aboutUs(request):
    return render(request,'ritu_web_app/aboutUs.html')
def contactUs(request):
    if(request.method=="POST"):
        name=request.POST['name']
        email=request.POST['email']
        message=request.POST['message']
        if(Messages.objects.create(name=name,email=email,message=message)):
            messages.info(request,'Your message is stored successfully')
        else:
            messages.info(request,"An unexpected error occured")
            
    return render(request,'ritu_web_app/contactUs.html')
def finalMessage(request):
    return render(request, 'ritu_web_app/FinalMessege.html')
def showLeaderboard(request):
    
    leaderboard=updatedLeaderboard.Leaderboards()
    data=leaderboard.showLeaderboardTable()
    
    # playerid=[]
    # name=[]
    # earnedPoints=[]
    # for i in range (len(data['data'])):
           
    #     playerid.append(data['data'][i]['playerid']) 
    #     name.append(data['data'][i]['name'])
    #     earnedPoints.append(data['data'][i]['earnedPoints'])    
    
    context={'datas':data,
    }
    print(context)
    #print(context)
    return render(request, 'ritu_web_app/Leaderboard.html',context)

def marketplace(request):
    
    product=marketPlace.Market()
    context=product.showProducts()
    if request.method=="POST":
        productID=request.POST['productID']
        name=request.POST['name']
        address=request.POST['address']
        contact=request.POST['contact']
        playerID = request.user.username
        
        order=orders.TrackOrder(playerID,productID,name,address,contact)
        if(order.addOrder()):
            messages.info(request,'Purchase Confirmed!')
        else:
            messages.info(request,'Unexpected Error Occured! Enter correct Product ID')
        
    return render(request, 'ritu_web_app/Marketplace.html',context)

    
def task1(request):
    if request.method=="POST":
        text=request.POST['task_1_url']
        file=request.FILES.get('file')
        player = request.user.username
        
        #Calculating score
        timeInMilli = int(round(time.time() * 1000)) #getting current time
        
        date_obj = datetime.strptime('01.09.2022 00:00:00,00','%d.%m.%Y %H:%M:%S,%f') #getting the time of when the task was launched 
        endTimeinMilli =int(date_obj.timestamp() * 1000)
        
        gapOfTimeInMilli=endTimeinMilli-timeInMilli #findin the time gap 
        
        point=round(0.00000014452*float(gapOfTimeInMilli),5) #rounding off points to 5 decimal digits
        points=str(point)
        
        #populating table with datas
        addingUrl=addTextTask.TextUrl(points,text,player)
        addingUrl.addTextUrl_1()
        addingUrl.addTextProof_1(file)
        
        
        #inserting data in leaderboard
        
        addingInLeaderboard=updatedLeaderboard.Leaderboards(player)
        addingInLeaderboard.insertDataInLeaderboard()
        
        
        
        return redirect('ritu_web_app:task2')

    return render(request, 'ritu_web_app/task1.html')
def task2(request):
    if request.method=="POST":
        text=request.POST['task_2_url']
        file=request.FILES.get('file')
        player = request.user.username
        
        #Calculating score
        timeInMilli = int(round(time.time() * 1000)) #getting current time
        
        date_obj = datetime.strptime('01.09.2022 00:00:00,00','%d.%m.%Y %H:%M:%S,%f') #getting the time of when the task was launched 
        endTimeinMilli =int(date_obj.timestamp() * 1000)
        
        gapOfTimeInMilli=endTimeinMilli-timeInMilli #findin the time gap 
        
        point=round(0.00000014452*float(gapOfTimeInMilli),5) #rounding off points to 5 decimal digits
        points=str(point)
        
        #populating table with datas
        addingUrl=addTextTask.TextUrl(points,text,player)
        addingUrl.addTextUrl_2()
        print(file)
        addingUrl.addTextProof_2(file)
        
        addingInLeaderboard=updatedLeaderboard.Leaderboards(player)
        addingInLeaderboard.insertDataInLeaderboard()
        
        return redirect('ritu_web_app:task3')
    return render(request, 'ritu_web_app/task2.html')
def task3(request):
    if request.method=="POST":
        text=request.POST['task_3_url']
        file=request.FILES.get('file')
        player = request.user.username
        
        #Calculating score
        timeInMilli = int(round(time.time() * 1000)) #getting current time
        
        date_obj = datetime.strptime('01.09.2022 00:00:00,00','%d.%m.%Y %H:%M:%S,%f') #getting the time of when the task was launched 
        endTimeinMilli =int(date_obj.timestamp() * 1000)
        
        gapOfTimeInMilli=endTimeinMilli-timeInMilli #findin the time gap 
        
        point=round(0.00000014452*float(gapOfTimeInMilli),5) #rounding off points to 5 decimal digits
        points=str(point)
        
        #populating table with datas
        addingUrl=addTextTask.TextUrl(points,text,player)
        addingUrl.addTextUrl_3()
        addingUrl.addTextProof_3(file)
        
        addingInLeaderboard=updatedLeaderboard.Leaderboards(player)
        addingInLeaderboard.insertDataInLeaderboard()
        
        return redirect('ritu_web_app:finalMessage')
    return render(request, 'ritu_web_app/task3.html')
def verification(request):
    return render(request,'ritu_web_app/verificationPage.html')
def profileCard(request):
    username = request.user.username
    playerdata=player.Player(username)
    context=playerdata.getInfo()
    
    if request.method=="POST" and request.FILES['picture']:
        file=request.FILES['picture']
        forimage=Players.objects.get(username=username)
        forimage.picture=file
        forimage.save()
        playerdata2=player.Player(username)
        context2=playerdata2.getInfo()
        
        return render(request,'ritu_web_app/profileCard.html',context2)
    
    return render(request,'ritu_web_app/profileCard.html',context)

def FinalMessege(request):
    return render(request,'ritu_web_app/FinalMessege.html')
def order(request):
    return render(request,'order.html')

ritu_web_app/templates/ritu_web_app/FinalMessege.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>RITU</title>

    <link rel="stylesheet" href="{% static 'task1.css' %}">
    <script src="https://kit.fontawesome.com/f6a195ab53.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>

  </head>
  <body>

    <nav class="navbar">
      <div class="max-width">
        <div class="logo"><a href="#"><span>R</span>itu.</span></a></div>
        <ul class="menu">
          <li class="nav-item"><a class="nav-link" href="{% url 'users:menu' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:profileCard' %}">Profile</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'ritu_web_app:leaderboard' %}">Leaderboard</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:marketplace' %}">Marketplace</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:homepage' %}">Log Out</a></li>
        </ul>
      </div>
    </nav>

    <section class = "home" id= "home">
      <div class="max-width">
        <div class="home-content">
          <div class="text-2">Game<span>Over</span></div>
          <div class="countDownTimer">
            <span><p class="timeRemaining">Time Remaining:</p></span>
            <span>
              <div class="timer">
                <div class="dayTime">
                  <h4 class="day">Time</h4>
                  <h5 class="tt">Day</h5>
                </div>
                <div class="dayTime">
                  <h4 class="hour">Time</h4>
                  <h5 class="tt">Hour</h5>
                </div>
                <div class="dayTime">
                  <h4 class="minute">Time</h4>
                  <h5 class="tt">Minute</h5>
                </div>
                <div class="dayTime">
                  <h4 class="second">Time</h4>
                  <h5 class="tt">Second</h5>
                </div>
              </div>
            </span>
          </div>   
          <div class="text-3">Thank you for playing with us! <br><span class="typing"></span></div>
          <a href="{% url 'ritu_web_app:leaderboard' %}">Leaderboard</a>
      </div>
    </section>

  <script src="{% static 'FinalMessage.js' %}"></script>
  <script src="{% static 'tasktime.js' %}"></script>
  </body>
</html>

ritu_web_app/templates/ritu_web_app/Leaderboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>RITU</title>

    <link rel="stylesheet" href="{% static 'leaderboard.css' %}">
    <script src="https://kit.fontawesome.com/f6a195ab53.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>

  </head>
  <body>

    <nav class="navbar">
      <div class="max-width">
        <div class="logo"><a href="#"><span>R</span>itu.</span></a></div>
        <ul class="menu">
          <li class="nav-item"><a class="nav-link" href="{% url 'users:menu' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:profileCard' %}">Profile</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'ritu_web_app:leaderboard' %}">Leaderboard</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:marketplace' %}">Marketplace</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:homepage' %}">Log Out</a></li>
        </ul>
      </div>
    </nav>

    <section class = "home" id= "home">
      <div class="max-width">
        <div class="home-content">
          <div class="text-2"><span>LEADER</span>BOARD</div>
          <div class="leaderboard_table">
            <table style="width:100%">
                <thead>
                  <tr>
                    <th>Player ID</th>
                    <th>Name</th>
                    <th>Points</th>
                  </tr>
                  {% for data in datas %}
                  <tr>
                      <td>{{ data.playerid }}</td>
                      <td>{{ data.name }}</td>
                      <td>{{ data.earnedPoints }}</td>
                  </tr>
                  {% endfor %}
                </thead>
                <tbody id="tableData"></tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

ritu_web_app/templates/ritu_web_app/Marketplace.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>RITU</title>

    <link rel="stylesheet" href="{% static 'marketplace.css' %}">
    {% comment %} <link rel="stylesheet" href="marketplace.css"> {% endcomment %}
    <script src="https://kit.fontawesome.com/f6a195ab53.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>

  </head>
  <body>

    <nav class="navbar">
      <div class="max-width">
        <div class="logo"><a href="#"><span>R</span>itu.</span></a></div>
        <ul class="menu">
          <li class="nav-item"><a class="nav-link" href="{% url 'users:menu' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:profileCard' %}">Profile</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'ritu_web_app:leaderboard' %}">Leaderboard</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:marketplace' %}">Marketplace</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:homepage' %}">Log Out</a></li>
        </ul>
      </div>
    </nav>

    <section class = "home" id= "home">
      <div class="max-width">
        <div class="home-content">
          <div class="text-2"><span>MARKET</span>PLACE</div>
          <div class="raise-error">
            {% for message in messages %}
              <p class="message">{{message}}</p>
            {% endfor %}
          </div>
            <div class="marketpalce-wrapper">
              <div class="container">
                 
                  {% for product in productData %}
                  <div class="box">
                    <img src='{{MEDIA_URL}}{{ product.product_img }}'>
                    <h3>{{ product.product_name }}</h3>
                    <p>{{ product.product_desc }}</p>
                    <p class="price">BDT {{ product.product_price }}</p>
                    <p>Product ID : {{ product.id }}</p>
                    <a href="#divOne" class="btn">Buy</a>
                  </div>
                  {% endfor %}
              
              </div>
            </div>
          
        </div>
      </div>
      <div class="overlay" id="divOne">
        <div class="wrapper">
          <h2>Please Fill up The Form</h2><a class="close" href="#">&times;</a>
          <div class="content">
            <div class="container">
              
              <form method="POST", action="marketplace">
                {% csrf_token %}
                <label>Full Name</label>
                <input placeholder="Your name.." type="text" name='name'>
                <label>Address</label>
                <input placeholder="Your full address.." type="text" name='address'>
                <label>Contact No.</label>
                <input placeholder="Your contact no.." type="text" name='contact'>
                <label>Enter Product ID</label> 
                <input placeholder="Product ID.." type="text" name='productID'>
                <input type="submit" value="Confirm Purchase">
              </form>
              
            </div>
          </div>
        </div>
      </div>
    </section>

    


  </body>
</html>

ritu_web_app/templates/ritu_web_app/profileCard.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>RITU</title>

    <link rel="stylesheet" href="{% static 'profileCard.css' %}">
    
    <script src="https://kit.fontawesome.com/f6a195ab53.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>

  </head>
  <body>

    <nav class="navbar">
      <div class="max-width">
        <div class="logo"><a href="#"><span>R</span>itu.</span></a></div>
        <ul class="menu">
          <li class="nav-item"><a class="nav-link" href="{% url 'users:menu' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:profileCard' %}">Profile</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'ritu_web_app:leaderboard' %}">Leaderboard</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:marketplace' %}">Marketplace</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:homepage' %}">Log Out</a></li>
        </ul>
      </div>
    </nav>
    <div class="profile-card">
      <div class="card-header">
        <div class="picture">
          <img src='{{MEDIA_URL}}{{picture}}'>
        </div>
        <div class="name">{{name}}</div>
        <div class="username">Username: {{username}}</div>
        <div class="mon">Contact No: {{mobileNum}}</div>
        <div class="address">Address: {{address}}</div>
        
        <form method="POST" action="profile" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="picture-upload">
          
          <label class="details">Change Profile Picture:</label>
          <span><input type="file" name="picture"></span>
          <input type="submit" class="submit-btn",value="Change">
        </div>
        <div class="gameInfo">
          <div class="numbers">
            <div class="tasks">
              <span class="points">{{task1point}}</span>
              <p class="time">{{task1time}}</p>
              Task1
            </div>
            <div class="tasks">
              <span class="points">{{task2point}}</span>
              <p class="time">{{task2time}}</p>
              Task2
            </div>
            <div class="tasks">
              <span class="points">{{task3point}}</span>
              <p class="time">{{task3time}}</p>
              Task3
            </div>
          </div>
        </div>
        
      </div>
    </div>
    
  </body>
</html>

ritu_web_app/templates/ritu_web_app/task1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Task 1</title>

    <link rel="stylesheet" href="{% static 'task1.css' %}">
    
    <script src="https://kit.fontawesome.com/f6a195ab53.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>

  </head>
  <body>

    <nav class="navbar">
      <div class="max-width">
        <div class="logo"><a href="#"><span>R</span>itu.</a></div>
        <ul class="menu">
          <li class="nav-item"><a class="nav-link" href="{% url 'users:menu' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:profileCard' %}">Profile</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'ritu_web_app:leaderboard' %}">Leaderboard</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:marketplace' %}">Marketplace</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'ritu_web_app:homepage' %}">Log Out</a></li>
        </ul>
      </div>
    </nav>

    <section class = "home" id= "home">
      <div class="max-width">
        <div class="home-content">
            <div class="text-2">Task<span> 1</span>
          </div>
          <div class="text-3">Trees help us fight the battle against Carbon Dioxide emissions!<br>
            Start your journey at RITU by planting a tree. It can be in a pot plant or in a field or garden<br>
            All you have to do, is record yourself planting it and upload it here. <br><span class="typing"></span><br><span class="typing_1"></span>
          </div>
          <div class="countDownTimer">
            <span><p class="timeRemaining">Time Remaining:</p></span>
            <span>
              <div class="timer">
                <div class="dayTime">
                  <h4 class="day">Time</h4>
                  <h5 class="tt">Day</h5>
                </div>
                <div class="dayTime">
                  <h4 class="hour">Time</h4>
                  <h5 class="tt">Hour</h5>
                </div>
                <div class="dayTime">
                  <h4 class="minute">Time</h4>
                  <h5 class="tt">Minute</h5>
                </div>
                <div class="dayTime">
                  <h4 class="second">Time</h4>
                  <h5 class="tt">Second</h5>
                </div>
              </div>
            </span>
          </div>
            <form method="POST" action="task1" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="user-details">
  
                <div class="file_upload_container">
                  <span class="details">Photo/Video Proof: </span>
                  <span class="fileInput"><input type="file" name="file" class="upload-box"/></span>
                </div>

                <div class="input-box">
                  <span class="details2">Enter Post Link: </span>
                  <span class="textInput"><input type="text" placeholder="Enter Links" required name="task_1_url" class="link-box"></span>
                </div>
              </div> 
              <div class="button">
                <input type="submit" value="Report">
              </div>
            </form>
      </div>
    </section>

            <!-- footer section start -->
            <!-- <footer>
              <div>
              <span>Created By <a href="#">Zaed Absara Farhan</a>    |  <span  class="far fa-copyright"></span>  2022 All rights reserved.</span>
              </div>
            </footer> -->

  <script src="{% static 'task.js' %}"></script>
  <script src="{% static 'tasktime.js' %}"></script>
  </body>

</html>